<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Dependency\Cassie.DependencyInjection.Extensions\Cassie.DependencyInjection.Extensions.csproj" />
    <ProjectReference Include="..\Cassie.Application\Cassie.Application.csproj" />
    <ProjectReference Include="..\Cassie.Domain\Cassie.Domain.csproj" />
  </ItemGroup>

</Project>
